name: aylanah
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57035
title: Ideas + Inspirations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8dee6'
    - '#bdabaf'
    - '#4d3f3e'
    - '#050100'
    - '#730716'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
